version: 2
jobs:
  deploy-staging:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo apt-get -y -qq install awscli
      - run: aws s3 sync build s3://nyc-babyface-staging/ --delete
      #- run: aws configure set preview.cloudfront true
      #- run: aws cloudfront create-invalidation --distribution-id E1WWN2CKZHK9Z7 --paths '/*'

  deploy-production:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo apt-get -y -qq install awscli
      - run: aws s3 sync build s3://nyc-babyface-production/ --delete
      #- run: aws configure set preview.cloudfront true
      #- run: aws cloudfront create-invalidation --distribution-id E1WWN2CKZHK9Z7 --paths '/*'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: staging
      - deploy-production:
          filters:
            branches:
              only: production
